name: Build and Deploy to aliyun

on:
  push:
    branches: [ "master" ]

# Environment variables available to all jobs and steps in this workflow.
env:
  REGION_ID: cn-qingdao
  REGISTRY: crpi-jufwe66303jo64ds.cn-qingdao.personal.cr.aliyuncs.com
  NAMESPACE: zkq_docker1
  TAG: V1.4
  ACK_DEPLOYMENT_NAME: nginx-deployment
  INSTANCE_ID: crpi-jufwe66303jo64ds

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # 1.1 Login to ACR
    - name: Login to ACR with the AccessKey pair
      run: |
        docker login --username=${{ secrets.ACCESS_KEY_ID }} --password=${{ secrets.ACCESS_KEY_SECRET }} $REGISTRY
       
    # 1.2 Build and push image to ACR
    - name: Build and push image to ACR
      run: |
        docker build . --file Dockerfile.aarch64 --tag "$REGISTRY/$NAMESPACE/${{ secrets.IMAGE }}:$TAG"
        docker push "$REGISTRY/$NAMESPACE/${{ secrets.IMAGE }}:$TAG" 
